### ISSUE TITLE
dbNSFP VEP plugin error "transcript_match parameter specified but..." -> due to corrupt dbNSFP4.3a.zip

### ISSUE THREAD

**Issue by Chris-lang478** [ntm/grexome-TIMC-Secondary#2]
@ntm 
Thanks for your great work!

I am trying to use your pipline in local system. However, when I run the secondary part, I just met:
WARNING: Failed to instantiate plugin dbNSFP: ERROR: transcript_match parameter specified but transcript-specific field detection failed at /xxxxx/ensembl-vep-107.0-0/dbNSFP.pm line 299.

Thses were my steps.
wget ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP4.3a.zip
unzip dbNSFP4.3a.zip
zcat dbNSFP4.3a_variant.chr1.gz | head -n1 > h
zgrep -h -v ^#chr dbNSFP4.3a_variant.chr* | sort -T /path/to/tmp_folder -k1,1 -k2,2n - | cat h - | bgzip -c > dbNSFP4.3a_grch38.gz
 tabix -s 1 -b 2 -e 2 dbNSFP4.3a_grch38.gz
mv   dbNSFP4.3a_grch38.gz  dbNSFP4.3a.gz
mv   dbNSFP4.3a_grch38.gz.tbi  dbNSFP4.3a.gz.tbi

And I used  Homo sapiens cache 107_GRCh38.

I just can't figure out the problem. 
Looking forward your help.

Best wishes,
Chirs

**Comment by ntm** [comment]
Hi Chris,
thanks for your interest. Your issue is really with running VEP + the dbNSFP plugin, but we can try to solve it.
I suspect that your dbNSFP4.3a.gz file has a problem. Are you sure you actually have data in there, and not just the header line? For example if you run: `gunzip -c dbNSFP4.3a.gz | head -n 2` do you get one header line AND one data line?

Maybe try to generate that file again. The instructions from the plugin are not great because the sort takes time and can fill up /tmp and die, and the files are already sorted by coordinates anyways. I think it's much better to just list the files in correct order. The following is what I run, the resulting file should be the same but please try this (after `unzip dbNSFP4.3a.zip`):
```
zcat dbNSFP4.3a_variant.chr1.gz | head -n1 > h
zgrep -h -v ^#chr dbNSFP4.3a_variant.chr[1-9].gz dbNSFP4.3a_variant.chr1[0-9].gz dbNSFP4.3a_variant.chr2[0-2].gz dbNSFP4.3a_variant.chr[MXY].gz | cat h - | bgzip -c > dbNSFP4.3a.gz
tabix -s 1 -b 2 -e 2 dbNSFP4.3a.gz
```
Do you still have the issue when using this new dbNSFP4.3a.gz file?
Regards,
Nicolas

**Comment by Chris-lang478** [comment]
@ntm 
Nicolas,
Thanks for your great help! I checked my original dbNSFP4.3a.zip file and it was broken.
I used your code to generate the file and the VEP run well.

However,  after the run, Cohorts_Canonical,Cohort,Transcripts and Samples file is empty.

I don't have subcohort, so I just delete the step 9 subcohort in seconry.pl. And my test file is merged-gatk-gvcf from primary.pl of two patients.

The log file shows step1-6 no problem. Howerver, it shows wrong from step 7 and 8.
My config only has ovary for  7_filterAndReorderAll.pl.
SO should I modify the 7_filterAndReorderAll.pl?
Log file shows:
E 7_reorderColumns.pl: some newOrder titles were not found: GTEX_testis_RATIO
 And the following log file is completed, I don't what's wrong with it.
Use of uninitialized value $header in scalar [chomp] at  8_extractSamples.pl line 161.

Here is my command line and the log file:

perl clnsec_.pl --samples=sampleCLN.xlsx --infile=grexomes_gatk_merged_221005.g.vcf.gz --outdir=SecondaryAnalyses_TEST --config=sec_config.pm 2> grexomeTIMCsec_TEST.log 

 2022-10-09 09:44:17: clnsec_.pl - starting to run
I clnsec_.pl: variant-caller id GATK will be appended to all filenames
I 2022-10-09 09:44:18: 4_vcf2tsv.pl - starting to run
I 2022-10-09 09:44:18: 2_sampleData2genotypes.pl - starting to run
I 2022-10-09 09:44:18: 5_addGTEX.pl - starting to run
I 2022-10-09 09:44:18: 3_runVEP.pl - starting to run
I 2022-10-09 09:44:19: 6_extractCohorts.pl - starting to run
I 2022-10-09 09:44:19: 1_filterBadCalls.pl - starting to run
I 2022-10-09 10:08:48: 3_runVEP.pl - finished parsing/processing chrom chr1
I 2022-10-09 10:28:05: 3_runVEP.pl - finished parsing/processing chrom chr2
I 2022-10-09 10:30:08: 6_extractCohorts.pl - done processing batch 10
I 2022-10-09 10:34:37: 3_runVEP.pl - finished parsing/processing chrom chr3
I 2022-10-09 10:50:26: 3_runVEP.pl - finished parsing/processing chrom chr4
I 2022-10-09 10:54:30: 6_extractCohorts.pl - done processing batch 20
I 2022-10-09 11:02:14: 3_runVEP.pl - finished parsing/processing chrom chr5
I 2022-10-09 11:20:21: 3_runVEP.pl - finished parsing/processing chrom chr6
I 2022-10-09 11:25:54: 6_extractCohorts.pl - batchNum=30, adjusting batchSize down to 2403
I 2022-10-09 11:26:10: 6_extractCohorts.pl - done processing batch 30
I 2022-10-09 11:26:16: 6_extractCohorts.pl - batchNum=45, adjusting batchSize up to 15728
I 2022-10-09 11:26:21: 6_extractCohorts.pl - done processing batch 40
I 2022-10-09 11:30:53: 3_runVEP.pl - finished parsing/processing chrom chr7
I 2022-10-09 11:38:35: 3_runVEP.pl - finished parsing/processing chrom chr8
I 2022-10-09 11:42:04: 6_extractCohorts.pl - done processing batch 50
I 2022-10-09 11:49:35: 3_runVEP.pl - finished parsing/processing chrom chr9
I 2022-10-09 12:04:59: 3_runVEP.pl - finished parsing/processing chrom chr10
I 2022-10-09 12:11:53: 6_extractCohorts.pl - batchNum=60, adjusting batchSize down to 2873
I 2022-10-09 12:12:14: 6_extractCohorts.pl - done processing batch 60
I 2022-10-09 12:12:26: 6_extractCohorts.pl - done processing batch 70
I 2022-10-09 12:12:33: 6_extractCohorts.pl - batchNum=75, adjusting batchSize up to 10342
I 2022-10-09 12:22:39: 3_runVEP.pl - finished parsing/processing chrom chr11
I 2022-10-09 12:33:51: 6_extractCohorts.pl - done processing batch 80
I 2022-10-09 12:42:20: 3_runVEP.pl - finished parsing/processing chrom chr12
I 2022-10-09 12:52:59: 6_extractCohorts.pl - batchNum=90, adjusting batchSize down to 2131
I 2022-10-09 12:53:07: 6_extractCohorts.pl - done processing batch 90
I 2022-10-09 12:53:26: 6_extractCohorts.pl - batchNum=105, adjusting batchSize up to 11365
I 2022-10-09 12:53:28: 6_extractCohorts.pl - done processing batch 100
I 2022-10-09 12:53:54: 3_runVEP.pl - finished parsing/processing chrom chr13
I 2022-10-09 13:05:22: 3_runVEP.pl - finished parsing/processing chrom chr14
I 2022-10-09 13:08:34: 6_extractCohorts.pl - done processing batch 110
I 2022-10-09 13:18:19: 3_runVEP.pl - finished parsing/processing chrom chr15
I 2022-10-09 13:23:15: 6_extractCohorts.pl - batchNum=120, adjusting batchSize down to 3176
I 2022-10-09 13:23:32: 6_extractCohorts.pl - done processing batch 120
I 2022-10-09 13:31:43: 3_runVEP.pl - finished parsing/processing chrom chr16
I 2022-10-09 13:36:54: 6_extractCohorts.pl - done processing batch 130
I 2022-10-09 13:36:58: 6_extractCohorts.pl - batchNum=135, adjusting batchSize down to 1929
I 2022-10-09 13:37:15: 6_extractCohorts.pl - done processing batch 140
I 2022-10-09 13:37:21: 6_extractCohorts.pl - batchNum=150, adjusting batchSize up to 12077
I 2022-10-09 13:37:47: 6_extractCohorts.pl - done processing batch 150
I 2022-10-09 13:45:20: 3_runVEP.pl - finished parsing/processing chrom chr17
I 2022-10-09 13:58:15: 6_extractCohorts.pl - done processing batch 160
I 2022-10-09 13:58:23: 3_runVEP.pl - finished parsing/processing chrom chr18
I 2022-10-09 14:04:31: 6_extractCohorts.pl - batchNum=165, adjusting batchSize down to 3704
I 2022-10-09 14:17:30: 3_runVEP.pl - finished parsing/processing chrom chr19
I 2022-10-09 14:22:20: 6_extractCohorts.pl - done processing batch 170
I 2022-10-09 14:22:35: 6_extractCohorts.pl - batchNum=180, adjusting batchSize down to 1708
I 2022-10-09 14:22:42: 6_extractCohorts.pl - done processing batch 180
I 2022-10-09 14:22:51: 6_extractCohorts.pl - batchNum=195, adjusting batchSize up to 15372
I 2022-10-09 14:22:53: 6_extractCohorts.pl - done processing batch 190
I 2022-10-09 14:23:07: 3_runVEP.pl - finished parsing/processing chrom chr20
I 2022-10-09 14:30:01: 3_runVEP.pl - finished parsing/processing chrom chr21
I 2022-10-09 14:34:29: 6_extractCohorts.pl - done processing batch 200
I 2022-10-09 14:34:31: 3_runVEP.pl - finished parsing/processing chrom chr22
I 2022-10-09 14:43:06: 1_filterBadCalls.pl - ALL DONE, completed successfully!
I 2022-10-09 14:43:06: 3_runVEP.pl - finished parsing/processing chrom chrX
I 2022-10-09 14:43:06: 2_sampleData2genotypes.pl - ALL DONE, completed successfully!
I 2022-10-09 14:49:24: 3_runVEP.pl - finished parsing/processing chrom chrY
I 2022-10-09 14:49:43: 3_runVEP.pl - finished parsing/processing chrom chrM
I 2022-10-09 14:50:19: 3_runVEP.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:20: 4_vcf2tsv.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:20: 5_addGTEX.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:36: 6_extractCohorts.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:37: 7_filterAndReorderAll.pl - starting to run
E 7_reorderColumns.pl: some newOrder titles were not found: GTEX_testis_RATIO
I 2022-10-09 14:50:38: 7_filterAndReorderAll.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:39: 8_extractSamples.pl - starting to run
Use of uninitialized value $header in scalar [chomp]at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/8_extractSamples.pl line 161.
Use of uninitialized value $header in split at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/8_extractSamples.pl line 162.
E: 8_extractSamples.pl - couldn't find OMF_HV or OMF_OTHERCAUSE_HV in header of infile OMF.csv
I 2022-10-09 14:50:40: 8_extractSamples.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:42: 8_extractTranscripts.pl - starting to run
Use of uninitialized value $header in scalar chomp at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/8_extractTranscripts.pl line 213.
Use of uninitialized value $header in split at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/8_extractTranscripts.pl line 214.
E 8_extractTranscripts.pl: couldn't find one of HV/HET/OCHV/OCHET for OMF
I 2022-10-09 14:50:43: 8_addPatientIDs.pl - starting to run
I 2022-10-09 14:50:43: 8_addPatientIDs.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:43: 9_requireUndiagnosed.pl - starting to run
Use of uninitialized value $header in scalar chomp at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/9_requireUndiagnosed.pl line 66.
Use of uninitialized value $header in split at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/9_requireUndiagnosed.pl line 67.
E: 9_requireUndiagnosed.pl couldn't find one of HV/HET for OMF
I 2022-10-09 14:50:45: 8_addPatientIDs.pl - starting to run
I 2022-10-09 14:50:46: 8_addPatientIDs.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:46: 7_filterAndReorderAll.pl - starting to run
Use of uninitialized value $header in scalar chomp at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/7_filterVariants.pl line 69.
Use of uninitialized value $header in concatenation (.) or string at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/7_filterVariants.pl line 70.
Use of uninitialized value $header in split at /home/data/zlsz_01/CLN_dir/grexomePIP/grexome-TIMC-Secondary/7_filterVariants.pl line 73.
E 7_filterVariants.pl: title CANONICAL required by script but missing, some VEP columns changed?
I 2022-10-09 14:50:47: 7_filterAndReorderAll.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:49: 10_qc_checkCausal.pl - starting to run
I 2022-10-09 14:50:49: 10_qc_checkCausal.pl - ALL DONE, completed successfully!
I 2022-10-09 14:50:49: clnsec_.pl - ALL DONE, completed successfully!

Looking forward your reply!

Best reagrds,
Chris

**Comment by ntm** [comment]
Hi @Chris-lang478 
please open separate issues for separate problems, much easier to track and manage.
The original issue was due to a corrupt download of dbNSFP4.3a.zip, I'm closing this as fixed. Please open a new issue with the "E 7_reorderColumns.pl: some newOrder titles were not found: GTEX_testis_RATIO" error. You can just copy-paste the info from your latest comment. Thanks!
