### ISSUE TITLE
How to edit &subCohorts()  in config.pm?  W grexome-TIMC-secondary.pl: sub-cohort file  defined in &subCohorts() but this file doesn't exist. Skipping this sub-cohort

### ISSUE THREAD

**Issue by Chris-lang478** [ntm/grexome-TIMC-Secondary#6]
@ntm 
I have no subcohort file.
And I modify the confog.pm as 

sub subCohorts {
    my %subCohorts = ("" => "");
    return(\%subCohorts);
}

After I run the secondary.pl, the log file shows that W grexome-TIMC-secondary.pl: sub-cohort file  defined in &subCohorts() but this file doesn't exist. Skipping this sub-cohort.

Is there better way to modify the config.pm?
Thanks again for your attention and great work!

Best regards,
Chris

**Comment by ntm** [comment]
just declare an empty hash, ie:
my %subCohorts = ();

**Comment by Chris-lang478** [comment]
Thanks for your help!!! I finally run all successfully.
